In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold


## Features_dataset

In [2]:
df1 = pd.read_csv("dense_train.csv")

In [3]:
new_name = {'Unnamed: 0' : 'new_label'}

In [4]:
df1.rename(columns=new_name,inplace=True)

In [5]:
unique_values = df1['new_label'].unique()

In [6]:
unique_values

array(['NCGC00178831-03', 'NCGC00166114-03', 'NCGC00263563-01', ...,
       'NCGC00260828-01', 'NCGC00260687-01', 'NCGC00261465-01'],
      dtype=object)

In [7]:
df1.columns

Index(['new_label', 'AW', 'AWeight', 'Arto', 'BertzCT', 'Chi0', 'Chi1',
       'Chi10', 'Chi2', 'Chi3',
       ...
       'W3D', 'W3DH', 'WNSA1', 'WNSA2', 'WNSA3', 'WPSA1', 'WPSA2', 'WPSA3',
       'grav', 'rygr'],
      dtype='object', length=802)

In [8]:
#df1.drop(columns='new_label',inplace=True)
model_results = np.zeros((12,647))

## Label dataset

In [10]:
df2 = pd.read_csv("labels_train.csv")

In [11]:
new_name = {'Unnamed: 0' : 'new_label'}

In [12]:
df2.rename(columns=new_name,inplace=True)

In [13]:
df2

new_label  NR.AhR  NR.AR  NR.AR.LBD  NR.Aromatase  NR.ER  \
0      NCGC00178831-03     NaN    NaN        NaN           NaN    NaN   
1      NCGC00166114-03     NaN    NaN        NaN           NaN    NaN   
2      NCGC00263563-01     NaN    NaN        NaN           NaN    NaN   
3      NCGC00013058-02     NaN    NaN        NaN           NaN    NaN   
4      NCGC00167516-01     NaN    0.0        NaN           NaN    NaN   
...                ...     ...    ...        ...           ...    ...   
12055  NCGC00261292-01     0.0    0.0        0.0           0.0    0.0   
12056  NCGC00261245-01     0.0    0.0        0.0           NaN    NaN   
12057  NCGC00260828-01     0.0    0.0        0.0           0.0    0.0   
12058  NCGC00260687-01     0.0    0.0        0.0           0.0    0.0   
12059  NCGC00261465-01     0.0    0.0        0.0           0.0    NaN   

       NR.ER.LBD  NR.PPAR.gamma  SR.ARE  SR.ATAD5  SR.HSE  SR.MMP  SR.p53  
0            NaN            NaN     NaN       NaN     0.0     NaN     NaN  
1            NaN            NaN     NaN       NaN     0.0     NaN     NaN  
2            NaN            NaN     NaN       NaN     0.0     NaN     NaN  
3            NaN            NaN     NaN       NaN     1.0     NaN     NaN  
4            NaN            NaN     NaN       NaN     NaN     NaN     NaN  
...          ...            ...     ...       ...     ...     ...     ...  
12055        0.0            0.0     0.0       0.0     0.0     0.0     0.0  
12056        0.0            0.0     NaN       NaN     NaN     NaN     NaN  
12057        0.0            0.0     0.0       0.0     0.0     0.0     0.0  
12058        0.0            0.0     0.0       0.0     0.0     0.0     0.0  
12059        0.0            0.0     0.0       0.0     0.0     0.0     0.0  

[12060 rows x 13 columns]

## Removing coorelated features

In [14]:
correlation_matrix = df1.corr()
correlation_threshold = 0.7  # Set your correlation threshold value
correlated_features = set()
for i in range(1,len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > correlation_threshold:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)
X = df1.drop(columns=correlated_features)


C:\Users\AMAN YADAV\AppData\Local\Temp\ipykernel_9336\3385341697.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df1.corr()


In [155]:
def keep_selected_features(csv_path, selected_features):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(csv_path)
    # Keep only the selected features
    df_selected = df[selected_features]
    return df_selected


## Concaetenating labels and feature dataset

In [45]:
merged_df = pd.merge(X, df2, on='new_label', how='inner')

In [46]:
merged_df

new_label            AW  AWeight   Arto  Chi3ch  Chi4ch  Chi5ch  \
0      NCGC00178831-03  5.436720e+07   13.053  2.176     0.0     0.0   0.000   
1      NCGC00166114-03  1.268818e+07   22.123  2.065     0.0     0.0   0.000   
2      NCGC00263563-01  3.076932e+06   13.085  2.154     0.0     0.0   0.287   
3      NCGC00013058-02  7.168569e+07   12.832  2.029     0.0     0.0   0.000   
4      NCGC00167516-01  7.989702e+06   12.936  2.124     0.0     0.0   0.572   
...                ...           ...      ...    ...     ...     ...     ...   
12055  NCGC00261292-01  1.428572e+07   14.255  2.000     0.0     0.0   0.096   
12056  NCGC00261245-01  1.193182e+07   13.674  2.061     0.0     0.0   0.000   
12057  NCGC00260828-01  1.081800e+01   12.374  2.045     0.0     0.0   0.000   
12058  NCGC00260687-01  3.229000e+00   12.543  2.267     0.0     0.0   0.079   
12059  NCGC00261465-01  1.931035e+07   15.004  1.867     0.0     0.0   0.000   

       Chiv3c  Chiv4c  EstateVSA1  ...  NR.AR.LBD  NR.Aromatase  NR.ER  \
0       1.088   0.000      12.407  ...        NaN           NaN    NaN   
1       1.655   0.000     105.090  ...        NaN           NaN    NaN   
2       4.375   0.298      66.949  ...        NaN           NaN    NaN   
3       2.083   0.000       0.000  ...        NaN           NaN    NaN   
4       2.944   0.000     100.318  ...        NaN           NaN    NaN   
...       ...     ...         ...  ...        ...           ...    ...   
12055   0.321   0.000      12.407  ...        0.0           0.0    0.0   
12056   0.685   0.000      30.918  ...        0.0           NaN    NaN   
12057   3.310   0.354      22.396  ...        0.0           0.0    0.0   
12058   0.389   0.000       0.000  ...        0.0           0.0    0.0   
12059   0.943   0.037     128.848  ...        0.0           0.0    NaN   

       NR.ER.LBD  NR.PPAR.gamma  SR.ARE  SR.ATAD5  SR.HSE  SR.MMP  SR.p53  
0            NaN            NaN     NaN       NaN     0.0     NaN     NaN  
1            NaN            NaN     NaN       NaN     0.0     NaN     NaN  
2            NaN            NaN     NaN       NaN     0.0     NaN     NaN  
3            NaN            NaN     NaN       NaN     1.0     NaN     NaN  
4            NaN            NaN     NaN       NaN     NaN     NaN     NaN  
...          ...            ...     ...       ...     ...     ...     ...  
12055        0.0            0.0     0.0       0.0     0.0     0.0     0.0  
12056        0.0            0.0     NaN       NaN     NaN     NaN     NaN  
12057        0.0            0.0     0.0       0.0     0.0     0.0     0.0  
12058        0.0            0.0     0.0       0.0     0.0     0.0     0.0  
12059        0.0            0.0     0.0       0.0     0.0     0.0     0.0  

[12060 rows x 161 columns]

In [47]:
merged_df.fillna(0,inplace=True)

In [48]:
merged_df.drop(columns="new_label",inplace=True)

## Predicting NR.AhR

In [59]:
columns_to_remove = ['NR.AR','NR.AR.LBD','NR.Aromatase','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_ahr = merged_df.drop(columns=columns_to_remove)

In [60]:
df_ahr 

AW  AWeight   Arto  Chi3ch  Chi4ch  Chi5ch  Chiv3c  Chiv4c  \
0      5.436720e+07   13.053  2.176     0.0     0.0   0.000   1.088   0.000   
1      1.268818e+07   22.123  2.065     0.0     0.0   0.000   1.655   0.000   
2      3.076932e+06   13.085  2.154     0.0     0.0   0.287   4.375   0.298   
3      7.168569e+07   12.832  2.029     0.0     0.0   0.000   2.083   0.000   
4      7.989702e+06   12.936  2.124     0.0     0.0   0.572   2.944   0.000   
...             ...      ...    ...     ...     ...     ...     ...     ...   
12055  1.428572e+07   14.255  2.000     0.0     0.0   0.096   0.321   0.000   
12056  1.193182e+07   13.674  2.061     0.0     0.0   0.000   0.685   0.000   
12057  1.081800e+01   12.374  2.045     0.0     0.0   0.000   3.310   0.354   
12058  3.229000e+00   12.543  2.267     0.0     0.0   0.079   0.389   0.000   
12059  1.931035e+07   15.004  1.867     0.0     0.0   0.000   0.943   0.037   

       EstateVSA1  EstateVSA10  ...  Petitj3D  RDFC10  RDFC13  RDFC22  RDFM3  \
0          12.407        0.000  ...     0.805  -0.337  -0.054   0.037  1.092   
1         105.090        0.000  ...     0.943  -0.588   0.747   0.000  6.182   
2          66.949        0.000  ...     0.763  -1.225   0.703  -0.664  3.068   
3           0.000        0.000  ...     0.732  -1.078  -0.060   0.296  2.047   
4         100.318        9.589  ...     0.893   1.149  -1.688  -0.757  2.705   
...           ...          ...  ...       ...     ...     ...     ...    ...   
12055      12.407        0.000  ...     0.706   0.376  -0.174   0.000  0.326   
12056      30.918        0.000  ...     0.827   0.550  -0.331  -0.021  0.961   
12057      22.396        0.000  ...     0.967  -0.589   0.081   0.087  0.907   
12058       0.000        0.000  ...     0.925  -0.039  -0.020   0.000  0.539   
12059     128.848        0.000  ...     0.948  -0.507   0.483  -0.263  1.135   

        RDFP5  RNCS     RPCS     grav  NR.AhR  
0       4.809     0   83.808   88.147     0.0  
1      33.221     0   46.958  134.852     0.0  
2      37.670     0    0.000  216.852     0.0  
3      33.235     0  700.786  238.265     0.0  
4      34.154     0  491.912  317.901     0.0  
...       ...   ...      ...      ...     ...  
12055   5.429     0  254.365   29.148     0.0  
12056  18.126     0  268.098   93.636     0.0  
12057  24.295     0  605.744   91.670     0.0  
12058   3.226     0   80.674   28.201     0.0  
12059  30.145     0  355.061   87.731     0.0  

[12060 rows x 149 columns]

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif

In [62]:
X = df_ahr.drop(columns=['NR.AhR'])  # FeaturesX = df_ahr.drop(columns=['new_label','NR.AhR'])  # Features
y = df_ahr['NR.AhR']  # Target variable


In [63]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
12055    0.0
12056    0.0
12057    0.0
12058    0.0
12059    0.0
Name: NR.AhR, Length: 12060, dtype: float64

In [64]:
X

AW  AWeight   Arto  Chi3ch  Chi4ch  Chi5ch  Chiv3c  Chiv4c  \
0      5.436720e+07   13.053  2.176     0.0     0.0   0.000   1.088   0.000   
1      1.268818e+07   22.123  2.065     0.0     0.0   0.000   1.655   0.000   
2      3.076932e+06   13.085  2.154     0.0     0.0   0.287   4.375   0.298   
3      7.168569e+07   12.832  2.029     0.0     0.0   0.000   2.083   0.000   
4      7.989702e+06   12.936  2.124     0.0     0.0   0.572   2.944   0.000   
...             ...      ...    ...     ...     ...     ...     ...     ...   
12055  1.428572e+07   14.255  2.000     0.0     0.0   0.096   0.321   0.000   
12056  1.193182e+07   13.674  2.061     0.0     0.0   0.000   0.685   0.000   
12057  1.081800e+01   12.374  2.045     0.0     0.0   0.000   3.310   0.354   
12058  3.229000e+00   12.543  2.267     0.0     0.0   0.079   0.389   0.000   
12059  1.931035e+07   15.004  1.867     0.0     0.0   0.000   0.943   0.037   

       EstateVSA1  EstateVSA10  ...  MoRSEV3  Petitj3D  RDFC10  RDFC13  \
0          12.407        0.000  ...   -0.325     0.805  -0.337  -0.054   
1         105.090        0.000  ...    2.296     0.943  -0.588   0.747   
2          66.949        0.000  ...    1.852     0.763  -1.225   0.703   
3           0.000        0.000  ...   -3.228     0.732  -1.078  -0.060   
4         100.318        9.589  ...   -6.318     0.893   1.149  -1.688   
...           ...          ...  ...      ...       ...     ...     ...   
12055      12.407        0.000  ...   -1.215     0.706   0.376  -0.174   
12056      30.918        0.000  ...   -2.362     0.827   0.550  -0.331   
12057      22.396        0.000  ...    1.161     0.967  -0.589   0.081   
12058       0.000        0.000  ...   -0.989     0.925  -0.039  -0.020   
12059     128.848        0.000  ...   -0.700     0.948  -0.507   0.483   

       RDFC22  RDFM3   RDFP5  RNCS     RPCS     grav  
0       0.037  1.092   4.809     0   83.808   88.147  
1       0.000  6.182  33.221     0   46.958  134.852  
2      -0.664  3.068  37.670     0    0.000  216.852  
3       0.296  2.047  33.235     0  700.786  238.265  
4      -0.757  2.705  34.154     0  491.912  317.901  
...       ...    ...     ...   ...      ...      ...  
12055   0.000  0.326   5.429     0  254.365   29.148  
12056  -0.021  0.961  18.126     0  268.098   93.636  
12057   0.087  0.907  24.295     0  605.744   91.670  
12058   0.000  0.539   3.226     0   80.674   28.201  
12059  -0.263  1.135  30.145     0  355.061   87.731  

[12060 rows x 148 columns]

In [65]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [66]:
Y_train

1374     0.0
3288     1.0
11969    0.0
11790    0.0
10095    0.0
        ... 
11964    0.0
5191     0.0
5390     0.0
860      0.0
7270     1.0
Name: NR.AhR, Length: 9648, dtype: float64

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_1 = RandomForestClassifier(n_estimators=150, random_state=42)

# Fit the classifier to your training data
rf_classifier_1.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=150, random_state=42)

In [69]:
predictions = rf_classifier_1.predict(X_test)

In [70]:
len(predictions)

2412

In [71]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 92.82752902155887


In [72]:
def prediction_model(test_set,model):
    predictions = model.predict(test_set)
    return predictions

## Predicting  NR.AR

In [73]:
columns_to_remove = ['NR.AhR','NR.AR.LBD','NR.Aromatase','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_ar = merged_df.drop(columns=columns_to_remove)

In [74]:
df_ar

AW  AWeight   Arto  Chi3ch  Chi4ch  Chi5ch  Chiv3c  Chiv4c  \
0      5.436720e+07   13.053  2.176     0.0     0.0   0.000   1.088   0.000   
1      1.268818e+07   22.123  2.065     0.0     0.0   0.000   1.655   0.000   
2      3.076932e+06   13.085  2.154     0.0     0.0   0.287   4.375   0.298   
3      7.168569e+07   12.832  2.029     0.0     0.0   0.000   2.083   0.000   
4      7.989702e+06   12.936  2.124     0.0     0.0   0.572   2.944   0.000   
...             ...      ...    ...     ...     ...     ...     ...     ...   
12055  1.428572e+07   14.255  2.000     0.0     0.0   0.096   0.321   0.000   
12056  1.193182e+07   13.674  2.061     0.0     0.0   0.000   0.685   0.000   
12057  1.081800e+01   12.374  2.045     0.0     0.0   0.000   3.310   0.354   
12058  3.229000e+00   12.543  2.267     0.0     0.0   0.079   0.389   0.000   
12059  1.931035e+07   15.004  1.867     0.0     0.0   0.000   0.943   0.037   

       EstateVSA1  EstateVSA10  ...  Petitj3D  RDFC10  RDFC13  RDFC22  RDFM3  \
0          12.407        0.000  ...     0.805  -0.337  -0.054   0.037  1.092   
1         105.090        0.000  ...     0.943  -0.588   0.747   0.000  6.182   
2          66.949        0.000  ...     0.763  -1.225   0.703  -0.664  3.068   
3           0.000        0.000  ...     0.732  -1.078  -0.060   0.296  2.047   
4         100.318        9.589  ...     0.893   1.149  -1.688  -0.757  2.705   
...           ...          ...  ...       ...     ...     ...     ...    ...   
12055      12.407        0.000  ...     0.706   0.376  -0.174   0.000  0.326   
12056      30.918        0.000  ...     0.827   0.550  -0.331  -0.021  0.961   
12057      22.396        0.000  ...     0.967  -0.589   0.081   0.087  0.907   
12058       0.000        0.000  ...     0.925  -0.039  -0.020   0.000  0.539   
12059     128.848        0.000  ...     0.948  -0.507   0.483  -0.263  1.135   

        RDFP5  RNCS     RPCS     grav  NR.AR  
0       4.809     0   83.808   88.147    0.0  
1      33.221     0   46.958  134.852    0.0  
2      37.670     0    0.000  216.852    0.0  
3      33.235     0  700.786  238.265    0.0  
4      34.154     0  491.912  317.901    0.0  
...       ...   ...      ...      ...    ...  
12055   5.429     0  254.365   29.148    0.0  
12056  18.126     0  268.098   93.636    0.0  
12057  24.295     0  605.744   91.670    0.0  
12058   3.226     0   80.674   28.201    0.0  
12059  30.145     0  355.061   87.731    0.0  

[12060 rows x 149 columns]

In [75]:
X = df_ar.drop(columns=['NR.AR'])
y = df_ar['NR.AR']  # Target variable


In [76]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
12055    0.0
12056    0.0
12057    0.0
12058    0.0
12059    0.0
Name: NR.AR, Length: 12060, dtype: float64

In [77]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [78]:
from sklearn.ensemble import RandomForestClassifier

In [79]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_2 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_2.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [80]:
predictions = rf_classifier_2.predict(X_test)

In [81]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.51741293532339


## Predicting NR.AR.LBD

In [82]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_ar_lbd = merged_df.drop(columns=columns_to_remove)

In [83]:
X = df_ar_lbd.drop(columns=['NR.AR.LBD'])
y = df_ar_lbd['NR.AR.LBD']  # Target variable


In [84]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [85]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_3 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_3.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [86]:
predictions = rf_classifier_3.predict(X_test)

In [87]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [88]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.60033167495854


## Predicting NR.Aromatase

In [89]:
columns_to_remove = ['NR.AhR','NR.AR','NR.AR.LBD','NR.ER','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_aromatase = merged_df.drop(columns=columns_to_remove)

In [90]:
X = df_aromatase.drop(columns=['NR.Aromatase'])
y = df_aromatase['NR.Aromatase']  # Target variable


In [91]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [92]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_4 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_4.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [93]:
predictions = rf_classifier_4.predict(X_test)

In [94]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [95]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.4759535655058


## Predicting NR.ER

In [96]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.AR.LBD','NR.ER.LBD','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_er= merged_df.drop(columns=columns_to_remove)

In [97]:
X = df_er.drop(columns=['NR.ER'])
y = df_er['NR.ER']  # Target variable


In [98]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [99]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_5 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_5.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [100]:
predictions = rf_classifier_5.predict(X_test)

In [101]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [102]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 92.74461028192371


## Predicting NR.ER.LBD

In [103]:
columns_to_remove = ['NR.AhR','NR.AR','NR.AR.LBD','NR.Aromatase','NR.ER','NR.PPAR.gamma','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_er_lbd = merged_df.drop(columns=columns_to_remove)

In [104]:
X = df_er_lbd.drop(columns=['NR.ER.LBD'])
y = df_er_lbd['NR.ER.LBD']  # Target variable


In [105]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [106]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_6 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_6.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [107]:
predictions = rf_classifier_6.predict(X_test)

In [108]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [109]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.35157545605307


## Predicting NR.PPAR.gamma

In [110]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [111]:
X = df_nr_ppar.drop(columns=['NR.PPAR.gamma'])
y = df_nr_ppar['NR.PPAR.gamma']  # Target variable


In [112]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [113]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_7 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_7.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [114]:
predictions = rf_classifier_7.predict(X_test)

In [115]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [116]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 97.92703150912106


## Predicting SR.ARE

In [117]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','NR.PPAR.gamma','SR.ATAD5','SR.HSE','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [118]:
X = df_nr_ppar.drop(columns=['SR.ARE'])
y = df_nr_ppar['SR.ARE']  # Target variable


In [119]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [120]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_8 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_8.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [121]:
predictions = rf_classifier_8.predict(X_test)

In [122]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [123]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 89.92537313432835


## Predicting SR.ATAD5

In [124]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','NR.PPAR.gamma','SR.HSE','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [125]:
X = df_nr_ppar.drop(columns=['SR.ATAD5'])
y = df_nr_ppar['SR.ATAD5']  # Target variable


In [126]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [127]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_9 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_9.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [128]:
predictions = rf_classifier_9.predict(X_test)

In [129]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [130]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 96.84908789386401


## Predicting SR.HSE

In [131]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','NR.PPAR.gamma','SR.MMP','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [132]:
X = df_nr_ppar.drop(columns=['SR.HSE'])
y = df_nr_ppar['SR.HSE']  # Target variable


In [133]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [134]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_10 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_10.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [135]:
predictions = rf_classifier_10.predict(X_test)

In [136]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [137]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 95.93698175787728


## Predicting SR.MMP

In [138]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','SR.HSE','NR.PPAR.gamma','SR.p53']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [139]:
X = df_nr_ppar.drop(columns=['SR.MMP'])
y = df_nr_ppar['SR.MMP']  # Target variable


In [140]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [141]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_11 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_11.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [142]:
predictions = rf_classifier_11.predict(X_test)

In [143]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [144]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 90.96185737976784


## Predicting SR.p53

In [145]:
columns_to_remove = ['NR.AhR','NR.AR','NR.Aromatase','NR.ER','NR.ER.LBD','NR.AR.LBD','SR.ARE','SR.ATAD5','SR.HSE','SR.MMP','NR.PPAR.gamma']
df_nr_ppar = merged_df.drop(columns=columns_to_remove)

In [146]:
X = df_nr_ppar.drop(columns=['SR.p53'])
y = df_nr_ppar['SR.p53']  # Target variable


In [147]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [148]:
# Create a RandomForestClassifier instance with desired parameters
# Example: n_estimators is the number of decision trees in the forest
rf_classifier_12 = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the classifier to your training data
rf_classifier_12.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [149]:
predictions = rf_classifier_12.predict(X_test)

In [150]:
predictions


array([0., 0., 0., ..., 0., 0., 0.])

In [151]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy:", accuracy*100)

Accuracy: 95.06633499170812


In [156]:
selected_features = X.columns
selected_features

Index(['AW', 'AWeight', 'Arto', 'Chi3ch', 'Chi4ch', 'Chi5ch', 'Chiv3c',
       'Chiv4c', 'EstateVSA1', 'EstateVSA10',
       ...
       'MoRSEV3', 'Petitj3D', 'RDFC10', 'RDFC13', 'RDFC22', 'RDFM3', 'RDFP5',
       'RNCS', 'RPCS', 'grav'],
      dtype='object', length=148)

In [157]:
test_df = keep_selected_features("dense_test.csv", selected_features)

In [158]:
prediction1 = prediction_model(test_df,rf_classifier_1)
model_results[0] = prediction1
prediction2 = prediction_model(test_df,rf_classifier_2)
model_results[1] = prediction2
prediction3 = prediction_model(test_df,rf_classifier_3)
model_results[2] = prediction3
prediction4 = prediction_model(test_df,rf_classifier_4)
model_results[3] = prediction4
prediction5 = prediction_model(test_df,rf_classifier_5)
model_results[4] = prediction5
prediction6 = prediction_model(test_df,rf_classifier_6)
model_results[5] = prediction6
prediction7 = prediction_model(test_df,rf_classifier_7)
model_results[6] = prediction7
prediction8 = prediction_model(test_df,rf_classifier_8)
model_results[7] = prediction8
prediction9 = prediction_model(test_df,rf_classifier_9)
model_results[8] = prediction9
prediction10 = prediction_model(test_df,rf_classifier_10)
model_results[9] = prediction10
prediction11 = prediction_model(test_df,rf_classifier_11)
model_results[10] = prediction11






In [159]:
model_results

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [160]:
columns_sum = np.sum(model_results, axis=0)
    
    
    
    
    

In [161]:
for i in range(len(columns_sum)):
    if(columns_sum[i]>=1):
        print("Efficiency: ", 1-(1/12)*columns_sum[i])
    else:
        print("Efficiency: 1")

Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency:  0.9166666666666666
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 1
Efficiency: 